# Generated by Django 4.1.6 on 2023-04-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
